services:
  api01: &api
    image: phaguiar/hackend:local
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instance0
    environment:
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

  api02:
    <<: *api 
    container_name: instance1

  nginx:
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./diag:/var/log/nginx
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "300MB"

  gatling:
    image: phaguiar/gatling:local
    build: ./experiment
    volumes:
      - ./experiment/load-test/user-files/results:/opt/gatling/results
      - ./experiment/load-test/user-files/simulations:/opt/gatling/user-files/simulations
      - ./experiment/conf/gatling.conf:/opt/gatling/conf/gatling.conf
      - ./experiment:/experiments
    stdin_open: true

  benchmarks:
    image: phaguiar/benchmarks:local
    build: ./Benchmarks
    profiles: ["manual-start"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
   
networks:
  default:
    driver: bridge
    name: hackend-network