services:
  ph-api01: &api
    image: phaguiar/hackend:local
    build: ./Server
    environment:
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      - phdb
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

  ph-api02:
    <<: *api

  ph-nginx: &nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./diag:/var/log/nginx
    depends_on:
      - ph-api01
      - ph-api02
    ports:
      - "10000:10000"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

  ph-nginx-exp:
    <<: *nginx
    volumes:
      - ./nginx-exp.conf:/etc/nginx/nginx.conf:ro
      - ./diag-exp:/var/log/nginx
    ports:
      - "10000:9999"
    profiles: ["manual-start"]

  phdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "300MB"

  gatling:
    image: phaguiar/gatling:local
    build: ./experiment
    volumes:
      - ./experiment/load-test/user-files/results:/opt/gatling/results
      - ./experiment/load-test/user-files/simulations:/opt/gatling/user-files/simulations
      - ./experiment/conf/gatling.conf:/opt/gatling/conf/gatling.conf
      - ./experiment:/experiments
    stdin_open: true
    profiles: ["manual-start"]

  benchmarks:
    image: phaguiar/benchmarks:local
    build: ./Benchmarks
    profiles: ["manual-start"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - phdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles: ["manual-start"]

volumes:
  pgadmin-data:
   
networks:
  default:
    driver: bridge
    name: hackend-network
