services:
  api01: &api
    image: phaguiar/hackend:local
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instance0
    environment:
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"

  api02:
    <<: *api 
    container_name: instance1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"

  gatling:
    image: phaguiar/gatling:local
    build: ./experiment
    volumes:
      - ./experiment:/experiment
    command: tail -f /dev/null

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
   
networks:
  default:
    driver: bridge
    name: hackend-network